version: '3.4'
services:
  golang:
    image: golang:1-stretch
    env_file: .env
    environment:
      BUILD_FOR_SCRATCH_IMAGE: "true"
    volumes:
      - .:/opt/envvars
    working_dir: /opt/envvars
