version: '3.4'
services:
  golang:
    image: flemay/golang:1-stretch
    volumes:
      - .:/go/src/github.com/flemay/envvars
    working_dir: /go/src/github.com/flemay/envvars

  envvars:
    image: flemay/envvars:0.0.3
    env_file: .env
    volumes:
      - .:/opt/app
    working_dir: /opt/app