version: '3.4'
services:
  golang:
    image: golang:1-stretch
    env_file: .env
    environment:
      BUILD_FOR_SCRATCH_IMAGE: "true"
    volumes:
      - .:/opt/envvars
    working_dir: /opt/app

  shellcheck:
    image: koalaman/shellcheck:latest
    network_mode: none
    volumes:
      - type: bind
        source: ./scripts
        target: /opt/app/scripts
    working_dir: /opt/app

  mockery:
    image: vektra/mockery:latest
    network_mode: none
    volumes:
      - type: bind
        source: ./pkg
        target: /opt/app/pkg
    working_dir: /opt/app
