version: '3.4'
services:
  golang:
    image: golang:1-stretch
    env_file: .env
    environment:
      BUILD_FOR_SCRATCH_IMAGE: "true"
    volumes:
      - type: bind
        source: .
        target: /opt/app
    working_dir: /opt/app

  shellcheck:
    image: koalaman/shellcheck:latest
    network_mode: none
    volumes:
      - type: bind
        source: ./scripts
        target: /opt/app/scripts
        read_only: true
    working_dir: /opt/app

  mockery:
    image: vektra/mockery:latest
    network_mode: none
    volumes:
      - type: bind
        source: .
        target: /opt/app
    working_dir: /opt/app

  golangcilint:
    image: golangci/golangci-lint:latest-alpine
    network_mode: none
    volumes:
      - type: bind
        source: .
        target: /opt/app
        read_only: true
    working_dir: /opt/app
