// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import envvars "github.com/flemay/envvars/pkg/envvars"
import mock "github.com/stretchr/testify/mock"

// DeclarationReader is an autogenerated mock type for the DeclarationReader type
type DeclarationReader struct {
	mock.Mock
}

// Read provides a mock function with given fields:
func (_m *DeclarationReader) Read() (*envvars.Declaration, error) {
	ret := _m.Called()

	var r0 *envvars.Declaration
	if rf, ok := ret.Get(0).(func() *envvars.Declaration); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*envvars.Declaration)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
