name: Release
on: create
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release
      run: "../../scripts/github_release.sh"
      env:
        DOCKER_USERNAME: flemaybot
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
