name: Release
on: create
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release
      run: make _ciRelease
      env:
        DOCKER_USERNAME: flemaybot
        DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
