name: Test
on:
  push:
    branches:
      - master
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
      - CODEOWNERS
  pull_request:
    branches:
      - master
    paths-ignore:
      - docs/**
      - README.md
      - LICENSE
      - CODEOWNERS
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: make ciTest
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
