name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: make ciTest
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
