name: Test
on:
  push:
    branches:
      - main
    paths-ignore: &ignoreList
      - docs/**
      - *.md
      - LICENSE
      - CODEOWNERS
  pull_request:
    branches:
      - main
    paths-ignore: *ignoreList
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: make ciTest
